from fastapi import APIRouter, HTTPException, UploadFile, File
from fastapi.responses import JSONResponse
from azure.storage.blob import BlobServiceClient, ContentSettings
import uuid
from dotenv import load_dotenv
import os, requests, logging

load_dotenv()

router = APIRouter()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize the BlobServiceClient with connection string
connection_string = os.getenv("BLOB_STORAGE_CONNECTION_STRING")
blob_service_client = BlobServiceClient.from_connection_string(connection_string)
container_name = os.getenv("BLOB_CONTAINER")

# Initialize the Computer Vision API client
cv_key = os.getenv("COMPUTER_VISION_KEY")
cv_endpoint = (
    os.getenv("COMPUTER_VISION_CONNECTION_STRING")
    + "computervision/imageanalysis:analyze?api-version=2023-04-01-preview"
)

# Initialize Azure OpenAI client
openai_key = os.getenv("OPENAI_KEY")
openai_endpoint = os.getenv("OPENAI_CONNECTION_STRING")


@router.get("/")
async def read_root():
    return {"message": "Welcome to SnapCaption!"}


@router.post("/upload_image")
async def upload_image(image: UploadFile = File(...)):
    # Generate a unique ID for the image
    image_id = str(uuid.uuid4())

    try:
        # Create a blob client using the unique ID as the name for the blob
        blob_client = blob_service_client.get_blob_client(
            container=container_name, blob=image_id
        )

        # Upload the image to blob storage
        image_data = await image.read()

        blob_client.upload_blob(
            image_data,
            overwrite=True,
            content_settings=ContentSettings(image.content_type),
        )

        # Generate a URL for the uploaded image
        image_url = blob_client.url
        print(f"Image uploaded. URL: {image_url}")

        return {
            "image_id": image_id,
            "image_url": image_url,
            "filename": image.filename,
            "message": "Image uploaded successfully",
        }
    except Exception as e:
        print(f"Error during image upload: {e}")  # Log the exact error
        raise HTTPException(status_code=500, detail=f"Failed to upload image: {str(e)}")


@router.get("/get_caption")
async def get_caption(image_url: str):
    """
    Generate a caption for the image using Azure Computer Vision.
    """
    # Define the request headers with the subscription key
    headers = {"Ocp-Apim-Subscription-Key": cv_key, "Content-Type": "application/json"}

    params = {"features": "denseCaptions", "language": "en"}

    # Define the data payload with the image URL
    data = {"url": image_url}

    try:
        # Make a request to the Computer Vision API
        response = requests.post(cv_endpoint, headers=headers, params=params, json=data)
        response.raise_for_status()  # Raise an error for non-200 responses
        result = response.json()

        # Extract the caption from the response
        if "denseCaptionsResult" in result:
            return result
        else:
            return JSONResponse(
                content={"caption": "No description available for the image."},
                status_code=404,
            )

    except requests.exceptions.RequestException as e:
        # Handle any request errors
        raise HTTPException(status_code=500, detail=f"Error generating caption: {e}")


@router.post("/generate_caption")
async def generate_caption(captions: list[str]):
    """
    Endpoint to process captions from Azure Computer Vision
    and refine them using Azure OpenAI.
    """
    # Validate the input
    if (
        not captions
        or not isinstance(captions, list)
        or not all(isinstance(c, str) for c in captions)
    ):
        raise HTTPException(
            status_code=400, detail="Invalid input: must provide a list of strings."
        )

    bullet_points = "\n".join(f"{caption}" for caption in captions)

    # Combine all captions into a single prompt for refinement
    prompt = f"The following captions were generated by a vision model:\n{bullet_points}\n\nProvide a more detailed and descriptive caption for the image overall:"

    print("Prompt: ", prompt)
    # Call Azure OpenAI API
    url = f"{openai_endpoint}"
    headers = {
        "Content-Type": "application/json",
        "api-key": openai_key,
    }
    payload = {
        "messages": [
            {
                "role": "system",
                "content": "You are an assistant that refines image captions.",
            },
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.2,
        "top_p": 0.5,
        "max_tokens": 200,  # Adjust based on your needs
    }

    logger.info(f"Payload: {payload}")

    try:
        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()

        # Parse the refined caption
        result = response.json()

        # Access the refined caption correctly
        if "choices" in result and len(result["choices"]) > 0:
            choice = result["choices"][0]
            if "message" in choice and "content" in choice["message"]:
                refined_caption = choice["message"]["content"].strip()
                logger.info(f"Refined Caption: {refined_caption}")
                return {"refined_caption": refined_caption}
            else:
                logger.error("Missing 'message' or 'content' in choice.")
                raise HTTPException(
                    status_code=500,
                    detail="Azure OpenAI API error: Missing 'message' or 'content' in response.",
                )
        else:
            logger.error("Missing 'choices' or 'choices' is empty in response.")
            raise HTTPException(
                status_code=500,
                detail="Azure OpenAI API error: Missing 'choices' in response.",
            )

    except requests.exceptions.HTTPError as http_err:
        # Extract error message from the response if available
        try:
            error_detail = (
                response.json().get("error", {}).get("message", str(http_err))
            )
        except Exception:
            error_detail = str(http_err)
        logger.error(f"Azure OpenAI API HTTP Error: {error_detail}")
        raise HTTPException(
            status_code=500, detail=f"Azure OpenAI API error: {error_detail}"
        )
    except KeyError as e:
        # Handle cases where the expected keys are not present in the response
        logger.error(f"KeyError: Missing key {str(e)} in the response.")
        raise HTTPException(
            status_code=500, detail=f"Error: Missing key {str(e)} in the response."
        )
    except Exception as e:
        logger.error(f"Unexpected Error: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error: {str(e)}")
