import requests
import json


def test_generate_caption(api_url, captions):
    """
    Sends a POST request to the /generate_caption endpoint with the provided captions.

    Args:
        api_url (str): The full URL to the /generate_caption endpoint.
        captions (list of str): A list of caption strings to send to the API.

    Returns:
        dict: The JSON response from the API containing the refined caption.
    """
    headers = {"Content-Type": "application/json"}

    try:
        # Send the POST request with the captions as a JSON array
        response = requests.post(api_url, headers=headers, json=captions)

        # Raise an exception for HTTP error codes
        response.raise_for_status()

        # Parse the JSON response
        data = response.json()

        # Check if 'refined_caption' is in the response
        if "choices" in data:
            print("Refined Caption:")
            print(json.dumps(data, indent=2))
        else:
            print("Unexpected response format:")
            print(json.dumps(data, indent=2))

    except requests.exceptions.HTTPError as http_err:
        print(f"HTTP error occurred: {http_err}")
        print(f"Response Content: {response.text}")
    except requests.exceptions.RequestException as req_err:
        print(f"Request exception occurred: {req_err}")
    except json.JSONDecodeError:
        print("Failed to parse JSON response.")
        print(f"Response Content: {response.text}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")


if __name__ == "__main__":
    # Define the API endpoint
    API_URL = "http://127.0.0.1:8000/generate_caption"  # Update if different

    # Your provided list of captions generated by Azure Computer Vision
    sample_captions = [
        "a hand holding a computer",
        "a hand holding a black device",
        "a close up of a black object",
        "a hand holding a computer",
        "a close-up of a toolbox",
        "a finger holding a black and red device",
        "a close up of a computer",
        "a close up of a circuit board",
        "a hand holding a black object",
        "a close-up of a black circle",
    ]

    # Test the API endpoint
    test_generate_caption(API_URL, sample_captions)
