name: CI/CD for SnapCaption

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Frontend and Backend
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker for containerization
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build and Push Docker Image for Backend
      - name: Build and push backend image to Google Cloud
        env:
          GOOGLE_PROJECT_ID: snapcaption-backend
          GOOGLE_COMPUTE_REGION: us-central1
          GCP_SERVICE_ACCOUNT_B64: ${{ secrets.GCP_SERVICE_ACCOUNT_B64 }}
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_B64 }}" | base64 --decode > gcloud-key.json
          gcloud auth activate-service-account --key-file=gcloud-key.json
          gcloud config set project $GOOGLE_PROJECT_ID
          gcloud builds submit --tag gcr.io/$GOOGLE_PROJECT_ID/snapcaption-backend2 ./snapcaption
          gcloud run deploy snapcaption-backend2 \
            --image gcr.io/$GOOGLE_PROJECT_ID/snapcaption-backend2 \
            --region $GOOGLE_COMPUTE_REGION \
            --platform managed \
            --allow-unauthenticated \
            --timeout 300

      # Deploy Frontend to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel --token=$VERCEL_TOKEN --prod --confirm
